apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cp-compute-services
  description: Handles hybrid connectivity requirements for subscription and dataplane lifecycles.
spec:
  owner: team-platform
  type: service
  lifecycle: production
  subcomponentOf: control-plane
