apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-components
  description: Parent component for TIBCO core platform services.
spec:
  owner: team-platform
  type: service
  lifecycle: production
  subcomponentOf: data-plane
