apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cp-email-service
  description: Sends out emails via SMTP, AWS SES, or SendGrid.
spec:
  owner: team-platform
  type: service
  lifecycle: production
  subcomponentOf: control-plane
