apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cp-user-subscriptions
  description: Provides backend APIs for managing subscriptions and related configurations.
spec:
  owner: team-platform
  type: service
  lifecycle: production
  subcomponentOf: control-plane
