apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: data-plane
  description: TIBCO Data Plane
  annotations:
    backstage.io/techdocs-ref: dir:docs/data-plane
  links:
    - url: "https://avv-est.com/tibco/hub/catalog/default/component/data-plane/docs/cp-dp-comm/"
      title: Control Plane - Data Plane Communication
      icon: dashboard
    - url: "https://avv-est.com/tibco/hub/catalog/default/component/data-plane/docs/capability-provisioning/"
      title: Capability Provisioning
      icon: dashboard
    - url: "https://avv-est.com/tibco/hub/catalog/default/component/data-plane/docs/int-capbility-topology/"
      title: Integration Capability Topology
      icon: dashboard
    - url: "https://avv-est.com/tibco/hub/catalog/default/component/data-plane/docs/app-provisioning/"
      title: App Provisioning Flow
      icon: dashboard
    - url: "https://avv-est.com/tibco/hub/catalog/default/component/data-plane/docs/observability/"
      title: Observability
      icon: dashboard
spec:
  owner: team-platform
  type: service
  lifecycle: production
  system: tibco-platform-system
