apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: data-plane
  description: TIBCO Data Plane
spec:
  owner: team-platform
  type: service
  lifecycle: production
  system: tibco-platform-system
