apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  description: Developer Hub capability.
  name: developer-hub
spec:
  owner: team-platform
  subcomponentOf: capabilities
  type: capability
  lifecycle: production
