apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hybrid-server
  description: Kubernetes operator acting as a proxy for hybrid connectivity.
spec:
  owner: team-platform
  type: service
  lifecycle: production
  subcomponentOf: control-plane
