apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hybrid-proxy
  description: Provides hybrid connectivity for a data plane.
spec:
  owner: team-platform
  type: service
  lifecycle: production
  subcomponentOf: control-plane
