apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cp-identity-management-service
  description: Authorizes users authenticated from IdPs; OAuth Server.
spec:
  owner: team-platform
  type: service
  lifecycle: production
  subcomponentOf: control-plane
