apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: router
  description: Kubernetes operator acting as a proxy for REST APIs.
spec:
  owner: team-platform
  type: service
  lifecycle: production
  subcomponentOf: control-plane
