apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tp-cp-pengine
  description: Enforces group- and user-based permissions.
spec:
  owner: team-platform
  type: service
  lifecycle: production
  subcomponentOf: control-plane
