apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tp-cp-monitoring-service
  description: Calculates DP and component traffic lights for monitoring status pages.
spec:
  owner: team-platform
  type: service
  lifecycle: production
  subcomponentOf: control-plane
