apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tp-cp-proxy
  description: Provides secure up-channel communication to CP from DP.
spec:
  owner: team-platform
  type: service
  lifecycle: production
  subcomponentOf: control-plane
