apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tp-cp-identity-provider
  description: Simple Identity Provider, authenticating users via passwords.
spec:
  owner: team-platform
  type: service
  lifecycle: production
  subcomponentOf: control-plane
