apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: web-servers
  description: Serves the main Web UI for Control Plane, enabling various user actions and integrations.
spec:
  owner: team-platform
  type: service
  lifecycle: production
  subcomponentOf: control-plane
