site_name: "TIBCO Platform Control Plane"
site_description: "TIBCO Platform Control Plane Documentation"

nav:
  - Introduction: index.md
  - Reference Architecture: platform-reference-architecture.md

plugins:
  - techdocs-core